from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ACTIVE_SUITE_PROCESS_FRAGMENTS = (
    "full_run.launch.sh",
    "run_suite_matrix.sh",
    "run_preflight.sh",
    "certify_suite_precheck.py",
    "audit_full_matrix.py",
    "run_full_matrix.py",
    "run_matrix_shard.sh",
    "_matrix_shard_launch.py",
    "run_reviewer_subset_pair.sh",
)
WINDOWS_REPO_RELATIVE_PROCESS_MARKERS = (
    "scripts/remote/run_suite_matrix.sh",
    "scripts/remote/run_preflight.sh",
    "scripts/remote/run_matrix_shard.sh",
    "scripts/remote/run_reviewer_subset_pair.sh",
    "scripts/run_full_matrix.py",
    "scripts/audit_full_matrix.py",
    "scripts/certify_suite_precheck.py",
    "scripts/clean_suite_outputs.py",
    "results/launchers/",
)

FIGURE_SKELETON_README = """# Full-Run Summary Figures

This directory is the repository-tracked export target for the publication-facing full-run figure surface.

In a fresh public clone, this directory may contain only this README until:

- a released raw full-run artifact is restored under `results/matrix/`, or
- the canonical full release suite is rerun locally and the figure export scripts are executed.

The release-candidate figure roster is intentionally narrow:

- `suite_all_models_methods_score_decomposition.*`
- `suite_all_models_methods_detection_vs_utility.*`

Exact-value leaderboards, utility-versus-robustness comparisons, sparse generalization views, source/model/language breakdowns, attack breakdowns, and timing-heavy comparisons are table-first artifacts under `results/tables/suite_all_models_methods/`.

Regenerate the canonical full figure/table surface with:

```bash
python scripts/reviewer_workflow.py regenerate --matrix-index results/matrix/suite_all_models_methods/matrix_index.json --figure-dir results/figures/suite_all_models_methods --table-dir results/tables/suite_all_models_methods
```

For a figure-only rerender of the generation-stage paper track after the canonical summary tables and the matching export-identity sidecar already exist, run `python scripts/render_materialized_summary_figures.py --table-dir results/tables/suite_all_models_methods --output-dir results/figures/suite_all_models_methods --export-identity results/tables/suite_all_models_methods/suite_all_models_methods_export_identity.json --require-times-new-roman`.
"""

TABLE_SKELETON_README = """# Full-Run Summary Tables

This directory is the repository-tracked export target for full-run summary tables.

In a fresh public clone, this directory may contain only this README until:

- a released raw full-run artifact is restored under `results/matrix/`, or
- the canonical full release suite is rerun locally and the table export scripts are executed.

Regenerate tables with:

```bash
python scripts/export_full_run_tables.py --matrix-index results/matrix/suite_all_models_methods/matrix_index.json --output-dir results/tables/suite_all_models_methods
```

The rerun-backed canonical table surface includes method-level, model-level, language-level, functional-quality, timing, and inventory exports under this directory.
"""

ENVIRONMENT_JSON_STUB = """{
  "label": "formal_execution_host_pre_rerun",
  "status": "sanitized_placeholder",
  "notes": [
    "The public repository snapshot does not preserve local preview machine details.",
    "Remote preflight regenerates the environment-of-record before any reviewer-visible rerun."
  ],
  "captured_fields": [
    "platform summary",
    "python executable and version",
    "release package versions",
    "toolchain availability",
    "gpu summary or unavailable status",
    "git revision"
  ]
}
"""

ENVIRONMENT_MD_STUB = """# Environment Capture

This repository snapshot intentionally keeps the public environment capture sanitized.

The canonical environment-of-record is regenerated by remote preflight on the execution host used for the reviewer-visible rerun. The files under `results/environment/` are therefore public-safe placeholders until that capture is refreshed.

## What Is Recorded

- host platform summary
- Python executable and version
- package versions relevant to the release workflow
- toolchain availability for the runtime matrix
- a GPU summary or an explicit unavailable status
- the git revision of the checked-out workspace

## How To Refresh

Use the capture script when you need to update the release-candidate environment record:

```bash
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python scripts/capture_environment.py --label formal_execution_host_pre_rerun --execution-mode single_host_canonical --output-json results/environment/runtime_environment.json --output-md results/environment/runtime_environment.md
```

The refreshed capture should be generated by remote preflight before any reviewer-visible rerun is published.
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Delete active suite outputs before a clean rerun.")
    parser.add_argument(
        "--include-full-matrix",
        action="store_true",
        help="Also remove active full-matrix outputs if present.",
    )
    parser.add_argument(
        "--include-release-bundle",
        action="store_true",
        help="Also remove the staged release bundle before the next clean rerun.",
    )
    parser.add_argument(
        "--preserve-precheck-artifacts",
        action="store_true",
        help="Keep benchmark audits, stage-A/stage-B matrix outputs, and suite-precheck receipts for post-gate inspection.",
    )
    parser.add_argument(
        "--preserve-launcher-artifacts",
        action="store_true",
        help="Keep results/launchers/* control surfaces when cleanup is running from an active detached launcher.",
    )
    parser.add_argument(
        "--extra-path",
        action="append",
        default=[],
        help=(
            "Also delete an explicit extra file or directory path under the repo root. "
            "Use this for host-local relay/smoke artifacts staged inside the repo; relay cleanup is not complete until "
            "those paths are removed too."
        ),
    )
    return parser.parse_args()


def _active_paths(
    *,
    include_full_matrix: bool,
    include_release_bundle: bool,
    preserve_precheck_artifacts: bool,
    preserve_launcher_artifacts: bool,
) -> list[Path]:
    paths = [
        ROOT / "results" / "archive",
        ROOT / "results" / "matrix" / "suite_all_models_methods" / "matrix_index.dry_run.json",
    ]
    paths.extend(sorted((ROOT / "results" / "matrix").glob("suite_reviewer_subset*")))
    paths.extend(sorted((ROOT / "results" / "matrix").glob("reviewer_subset*")))
    paths.extend(sorted((ROOT / "results" / "matrix" / "subsets").glob("suite_reviewer_subset*.json")))
    paths.extend(sorted((ROOT / "results" / "matrix" / "subsets").glob("reviewer_subset*.json")))
    paths.extend(sorted((ROOT / "results" / "environment").glob("suite_reviewer_subset*_runtime_environment.json")))
    paths.extend(sorted((ROOT / "results" / "environment").glob("suite_reviewer_subset*_runtime_environment.md")))
    paths.extend(sorted((ROOT / "results" / "environment").glob("reviewer_subset*_runtime_environment.json")))
    paths.extend(sorted((ROOT / "results" / "environment").glob("reviewer_subset*_runtime_environment.md")))
    paths.extend(sorted((ROOT / "results" / "certifications").glob("subset_a*")))
    paths.extend(sorted((ROOT / "results" / "certifications").glob("subset_b*")))
    paths.extend(sorted((ROOT / "results" / "certifications").glob("reviewer_subset*")))
    if not preserve_precheck_artifacts:
        paths.extend(
            [
                ROOT / "results" / "audits",
                ROOT / "results" / "matrix" / "suite_canary_heavy",
                ROOT / "results" / "matrix" / "model_invocation_smoke",
                ROOT / "results" / "figures" / "suite_precheck",
                ROOT / "results" / "tables" / "suite_precheck",
                ROOT / "results" / "certifications" / "suite_precheck_gate.local.json",
                ROOT / "results" / "certifications" / "suite_precheck_gate.json",
                ROOT / "results" / "certifications" / "suite_precheck.nohup.log",
                ROOT / "results" / "certifications" / "suite_precheck.live.log",
                ROOT / "results" / "certifications" / "suite_precheck.launch.json",
                ROOT / "results" / "fetched_suite",
            ]
        )
        if include_full_matrix:
            paths.extend(
                [
                    ROOT / "results" / "certifications" / "remote_preflight_receipt.json",
                    ROOT / "results" / "environment" / "runtime_environment.json",
                    ROOT / "results" / "environment" / "runtime_environment.md",
                    ROOT / "results" / "launchers" / ".remote_preflight.lock",
                ]
            )
    if include_full_matrix:
        paths.extend(
            [
                ROOT / "results" / "matrix" / "suite_all_models_methods",
                ROOT / "results" / "matrix_shards" / "suite_all_models_methods",
                ROOT / "results" / "certifications" / "suite_all_models_methods",
                ROOT / "results" / "figures" / "suite_all_models_methods",
                ROOT / "results" / "tables" / "suite_all_models_methods",
                ROOT / "results" / "certifications" / "suite_all_models_methods_gate.json",
                ROOT / "results" / "certifications" / "suite_all_models_methods.nohup.log",
                ROOT / "results" / "certifications" / "suite_all_models_methods.launch.json",
                ROOT / "results" / "certifications" / "suite_all_models_methods.monitor.txt",
                ROOT / "results" / "matrix" / "suite_all_models_methods" / ".matrix_runner.lock",
            ]
        )
        if not preserve_launcher_artifacts:
            paths.append(ROOT / "results" / "launchers" / "suite_all_models_methods")
        for root_name in ("matrix", "figures", "tables", "environment", "audits", "certifications"):
            paths.extend(sorted((ROOT / "results" / root_name).glob("suite_all_models_methods_shard_*")))
    if include_release_bundle:
        paths.extend(sorted((ROOT / "results").glob("release_bundle*")))
        tmp_root = ROOT / "results" / "tmp"
        if tmp_root.exists():
            paths.extend(sorted(tmp_root.iterdir()))
    paths.extend(sorted((ROOT / "results").glob("test_release_bundle*")))
    paths.extend(sorted((ROOT / "results").glob(".tmp_release_bundle*")))
    return paths


def _delete_path(path: Path) -> dict[str, str] | None:
    if not path.exists():
        return None
    symlink_component = _first_symlink_component(path)
    if symlink_component is not None:
        raise RuntimeError(
            f"refusing to clean suite outputs through symlinked path components: {symlink_component}"
        )
    if path.is_dir():
        shutil.rmtree(path)
    else:
        path.unlink()
    return {"deleted": str(path)}


def _first_symlink_component(path: Path) -> Path | None:
    try:
        relative = path.relative_to(ROOT)
    except ValueError:
        return path if path.is_symlink() else None
    current = ROOT
    if current.is_symlink():
        return current
    for part in relative.parts:
        current = current / part
        if current.is_symlink():
            return current
    return None


def _allowed_cleanup_roots() -> tuple[Path, ...]:
    return (
        ROOT / "tmp",
        ROOT / "results" / "tmp",
    )


def _resolve_extra_path(raw_path: str) -> Path:
    candidate = Path(str(raw_path).strip())
    if not str(candidate):
        raise ValueError("extra cleanup path must not be empty")
    absolute = candidate if candidate.is_absolute() else (ROOT / candidate)
    normalized = Path(os.path.abspath(str(absolute)))
    allowed_roots = tuple(Path(os.path.abspath(str(root))) for root in _allowed_cleanup_roots())
    if not any(normalized == root or root in normalized.parents for root in allowed_roots):
        allowed = ", ".join(str(root) for root in _allowed_cleanup_roots())
        raise ValueError(f"extra cleanup path must stay under one of: {allowed}")
    symlink_component = _first_symlink_component(normalized)
    if symlink_component is not None:
        raise ValueError(f"extra cleanup path must not traverse symlinked temp roots: {symlink_component}")
    return normalized


def _command_targets_repo(command: str, *, root_text: str) -> bool:
    normalized = command.replace("\\", "/")
    normalized_root = root_text.replace("\\", "/")
    return normalized_root in normalized


def _process_cwd(pid: int) -> Path | None:
    if os.name == "nt":
        return None
    try:
        return Path(os.readlink(f"/proc/{pid}/cwd")).resolve()
    except OSError:
        return None


def _process_targets_repo(pid: int, command: str, *, root_path: Path, root_text: str) -> bool:
    if _command_targets_repo(command, root_text=root_text):
        return True
    process_cwd = _process_cwd(pid)
    if process_cwd is None:
        if os.name == "nt":
            normalized = command.replace("\\", "/")
            return any(marker in normalized for marker in WINDOWS_REPO_RELATIVE_PROCESS_MARKERS)
        return False
    return process_cwd == root_path or root_path in process_cwd.parents


def _load_process_rows() -> list[tuple[int, int, str]]:
    if os.name == "nt":
        try:
            completed = subprocess.run(
                [
                    "powershell",
                    "-NoProfile",
                    "-Command",
                    (
                        "Get-CimInstance Win32_Process | "
                        "Select-Object ProcessId,ParentProcessId,CommandLine | "
                        "ConvertTo-Json -Compress"
                    ),
                ],
                check=True,
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",
            )
        except Exception:
            return []
        payload = completed.stdout.strip()
        if not payload:
            return []
        try:
            records = json.loads(payload)
        except json.JSONDecodeError:
            return []
        if isinstance(records, dict):
            records = [records]
        rows: list[tuple[int, int, str]] = []
        for record in records:
            if not isinstance(record, dict):
                continue
            try:
                pid = int(record.get("ProcessId"))
                ppid = int(record.get("ParentProcessId"))
            except (TypeError, ValueError):
                continue
            command = str(record.get("CommandLine") or "")
            rows.append((pid, ppid, command))
        return rows
    try:
        completed = subprocess.run(
            ["ps", "-eo", "pid=,ppid=,args="],
            check=True,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
        )
    except Exception:
        return []
    rows: list[tuple[int, int, str]] = []
    for line in completed.stdout.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        parts = stripped.split(None, 2)
        if len(parts) != 3:
            continue
        pid_text, parent_text, command = parts
        try:
            pid = int(pid_text.strip())
            ppid = int(parent_text.strip())
        except ValueError:
            continue
        rows.append((pid, ppid, command))
    return rows


def _active_cleanup_conflicts() -> list[str]:
    root_path = ROOT.resolve()
    root_text = str(root_path)
    current_pid = os.getpid()
    process_rows = _load_process_rows()
    parent_by_pid: dict[int, int] = {}
    for pid, ppid, _command in process_rows:
        parent_by_pid[pid] = ppid
    allowed_pids = {current_pid}
    cursor = current_pid
    while cursor in parent_by_pid and parent_by_pid[cursor] not in allowed_pids:
        cursor = parent_by_pid[cursor]
        allowed_pids.add(cursor)
    conflicts: list[str] = []
    for pid, _ppid, command in process_rows:
        if pid in allowed_pids:
            continue
        if not _process_targets_repo(pid, command, root_path=root_path, root_text=root_text):
            continue
        if not any(fragment in command for fragment in ACTIVE_SUITE_PROCESS_FRAGMENTS):
            continue
        conflicts.append(f"{pid} {command}")
    return conflicts


def _ensure_safe_to_clean() -> None:
    conflicts = _active_cleanup_conflicts()
    if conflicts:
        preview = "\n".join(conflicts[:8])
        raise RuntimeError(
            "refusing to clean suite outputs while active suite processes still exist for this repo:\n"
            f"{preview}"
        )


def _reset_export_target(directory: Path, *, placeholder_name: str, placeholder_text: str) -> dict[str, str]:
    symlink_component = _first_symlink_component(directory)
    if symlink_component is not None:
        raise RuntimeError(
            f"refusing to reset export target through symlinked path components: {symlink_component}"
        )
    if directory.exists():
        for child in directory.iterdir():
            if child.is_symlink():
                raise RuntimeError(
                    f"refusing to rewrite export placeholders through symlinked files: {child}"
                )
            if child.name == placeholder_name:
                continue
            if child.is_dir():
                shutil.rmtree(child)
            else:
                child.unlink()
    directory.mkdir(parents=True, exist_ok=True)
    placeholder_path = directory / placeholder_name
    if placeholder_path.is_symlink():
        raise RuntimeError(
            f"refusing to rewrite export placeholders through symlinked files: {placeholder_path}"
        )
    placeholder_path.write_text(placeholder_text.rstrip() + "\n", encoding="utf-8", newline="\n")
    return {"reset": str(directory), "placeholder": str(placeholder_path)}


def _reset_environment_placeholders() -> list[dict[str, str]]:
    environment_dir = ROOT / "results" / "environment"
    symlink_component = _first_symlink_component(environment_dir)
    if symlink_component is not None:
        raise RuntimeError(
            f"refusing to reset environment placeholders through symlinked path components: {symlink_component}"
        )
    environment_dir.mkdir(parents=True, exist_ok=True)
    json_path = environment_dir / "runtime_environment.json"
    md_path = environment_dir / "runtime_environment.md"
    for placeholder_path in (json_path, md_path):
        if placeholder_path.is_symlink():
            raise RuntimeError(
                f"refusing to rewrite environment placeholders through symlinked files: {placeholder_path}"
            )
    json_path.write_text(ENVIRONMENT_JSON_STUB.rstrip() + "\n", encoding="utf-8", newline="\n")
    md_path.write_text(ENVIRONMENT_MD_STUB.rstrip() + "\n", encoding="utf-8", newline="\n")
    return [
        {"reset": str(json_path), "placeholder": str(json_path)},
        {"reset": str(md_path), "placeholder": str(md_path)},
    ]


def main() -> int:
    args = parse_args()
    _ensure_safe_to_clean()
    deleted: list[dict[str, str]] = []
    include_full_matrix = args.include_full_matrix
    for path in _active_paths(
        include_full_matrix=include_full_matrix,
        include_release_bundle=args.include_release_bundle,
        preserve_precheck_artifacts=args.preserve_precheck_artifacts,
        preserve_launcher_artifacts=args.preserve_launcher_artifacts,
    ):
        item = _delete_path(path)
        if item is not None:
            deleted.append(item)
    for raw_extra_path in args.extra_path:
        extra_path = _resolve_extra_path(raw_extra_path)
        item = _delete_path(extra_path)
        if item is not None:
            deleted.append(item)
    for directory in (
        ROOT / "results",
        ROOT / "results" / "figures",
        ROOT / "results" / "tables",
        ROOT / "results" / "matrix",
        ROOT / "results" / "certifications",
    ):
        directory.mkdir(parents=True, exist_ok=True)
    if include_full_matrix:
        _reset_export_target(
            ROOT / "results" / "figures" / "suite_all_models_methods",
            placeholder_name="README.md",
            placeholder_text=FIGURE_SKELETON_README,
        )
        _reset_export_target(
            ROOT / "results" / "tables" / "suite_all_models_methods",
            placeholder_name="README.md",
            placeholder_text=TABLE_SKELETON_README,
        )
        if not args.preserve_precheck_artifacts:
            deleted.extend(_reset_environment_placeholders())
    print(json.dumps({"deleted_count": len(deleted), "deleted": deleted}, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
