record = {
    "task_id": "task_0001",
    "case_id": "case_0001",
    "model": "DeepSeek-Coder-6.7B-Instruct",
    "provider": "local_or_deepseek",
    "family": "deepseek-coder",
    "language": "python",
    "source_group": "crafted_stress",
    "attack_condition": "identifier_rename",
    "baseline_or_control": "SemCodebook-full",
    "prompt_hash": "sha256:...",
    "raw_payload_hash": "sha256:...",
    "structured_payload_hash": "sha256:...",
    "detector_version": "v1",
    "threshold_version": "frozen-v1",
    "score": 0.9726,
    "claim_bearing": True,
    "decision": "recover",
}
